# 每天6:30执行
# UTC 时间，北京时间需要 UTC+8
name: Start

on:  
   workflow_dispatch:  
   schedule:  
       - cron: '30 22 * * *'

jobs:
  TiebaSignIn:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v4.4.0
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v4.0.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
        BDUSS: ${{ secrets.BDUSS }}
        SCKEY: ${{ secrets.SCKEY }}
      run: |
        mvn compile exec:java -Dexec.mainClass="top.srcrs.Run" -Dexec.args="${BDUSS} ${SCKEY}"
